AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.6

  Include:
    - '**/*.rb'
    - '**/Rakefile'
    - '**/config.ru'

  Exclude:
    - 'db/**/*'

Documentation:
  Enabled: false

Style/AccessModifierDeclarations:
  Enabled: false

Security/YAMLLoad:
  Enabled: false

Metrics/LineLength:
  Max: 140

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'spec/spec_helper.rb'
    - 'spec/support/**/*.rb'

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: required
