AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.4

  Include:
    - '**/Rakefile'
    - '**/config.ru'

Documentation:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Style/SymbolArray:
  Enabled: true

Style/LambdaCall:
  Enabled: false

Style/FileName:
  Exclude:
    - 'Gemfile'

Style/FormatStringToken:
  Enabled: false

Security/YAMLLoad:
  Enabled: false

Metrics/LineLength:
  Max: 140

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'spec/spec_helper.rb'
    - 'spec/support/**/*.rb'
