version: "3"
services:
  api:
    build: .
    command: bundle exec rackup -o 0.0.0.0 -p 3000
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=postgres
    links:
      - db

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres

